[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
authors = ["Christian Moldenhauer"]

[dependencies]
chrono = "0.4"
to_vec = "0.1"
mexe = "0.2.0"
rayon = "1.7.0"
permute = "0.2.1"
iter_tools = "0.1.4"
regex = "1.9.3"
