[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
authors = ["Chris Mo"]

[dependencies]
rayon = "1.7.0"
iter_tools = "0.4.0"
regex = "1.9.5"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
